### ISSUE TITLE
Run as with '--here' instead in new window

### ISSUE THREAD

**Issue by petrikoz** [remiprev/teamocil#100]
Hi.

When I use my scenario without option '--here' new window create, but panes create in current window.

tmux 2.1, teamocil 1.2

Example scenario:

```yml

windows:
- name: 'example'
  layout: main-vertical
  root: '~/example/src'
  panes:
  - focus: true
    commands:
    - 'make dev.start'
  - commands:
    - 'ggpull'
  - commands:
    - 'tail gunicorn.log'
```

**Comment by remiprev** [comment]
Could you run your problematic layout with the `--debug` flag?

```bash
$ teamocil --debug layout_name
```

Please paste the output here :smile:

**Comment by petrikoz** [comment]
```
$ teamocil --debug example

tmux rename-session 'teamocil-session-229708'
tmux new-window -n 'example' -c '/home/user/example/src'
tmux send-keys -t 0 'make dev.start'
tmux send-keys -t 0 'Enter'
tmux select-layout 'main-vertical'
tmux split-window -c '/home/user/example/src'
tmux send-keys -t 1 'ggpull'
tmux send-keys -t 1 'Enter'
tmux select-layout 'main-vertical'
tmux split-window -c '/home/user/example/src'
tmux send-keys -t 2 'tail -f gunicorn.log'
tmux send-keys -t 2 'Enter'
tmux select-layout 'main-vertical'
tmux select-pane -t 0
```

**Comment by iven** [comment]
I think I have a similiar issue with tmux 2.1. New windows created, but all the commands run in the first window.

```
name: Banker
windows:
  - name: Django Server
    panes:
      - pew workon banker
  - panes:
      - pew workon banker
  - panes:
      - pew workon banker
  - panes:
      - pew workon banker
  - panes:
```

```
$ teamocil --here --debug banker
tmux rename-session 'Banker'
tmux rename-window 'Django Server'
tmux send-keys -t 'Django Server.0' 'pew workon banker'
tmux send-keys -t 'Django Server.0' 'Enter'
tmux select-pane -t Django Server.0
tmux new-window 
tmux send-keys -t '.0' 'pew workon banker'
tmux send-keys -t '.0' 'Enter'
tmux select-pane -t .0
tmux new-window 
tmux send-keys -t '.0' 'pew workon banker'
tmux send-keys -t '.0' 'Enter'
tmux select-pane -t .0
tmux new-window 
tmux send-keys -t '.0' 'pew workon banker'
tmux send-keys -t '.0' 'Enter'
tmux select-pane -t .0
tmux new-window 
tmux select-pane -t .0
```
