### ISSUE TITLE
Can we open a link using open yet close the pane after?

### ISSUE THREAD

**Issue by cggaurav** [remiprev/teamocil#102]

**Comment by remiprev** [comment]
Sure, you can do :

```yaml
windows:
  - name: test
    root: "/path/to/root"
    layout: tiled
    panes:
    - echo "First"
    - echo "Second"
    - open http://github.com; exit
```
