### ISSUE TITLE
Issue with emacsclient and teamocil (too fast?)

### ISSUE THREAD

**Issue by paxperscientiam** [remiprev/teamocil#103]
Not sure what is happening, but I noticed that if I set several windows to create new buffers with emacsclient, after (about) the 8th connection request, subsequent requests are refused.

The workaround for me is to "sleep" before making a new connection request.

Any thought about this? I'm thinking the core issue is that the emacs server is receiving requests too quickly, so maybe it's just a limitation of emacs.

**Comment by remiprev** [comment]
> The idea behind the above command is that the arguments would tell teamocil to only parse config data for window "Name1" and window "Name4." That's it in a nutshell.

I get the idea, but I don’t think this will ever be implemented in Teamocil. Layouts are meant to be defined as a set of windows. What you could do to reproduce that behavior is create a single layout for each of your window.

```yaml
```

**Comment by remiprev** [comment]
> The idea behind the above command is that the arguments would tell teamocil to only parse config data for window "Name1" and window "Name4." That's it in a nutshell.

I get the idea, but I don’t think this will ever be implemented in Teamocil. Layouts are meant to be defined as a set of windows. What you could do to reproduce that behavior is create a single layout for each of your window.

```yaml
# sample-1.yml
windows:
  - root: /Users/foo
    name: sample-1
    layout: even-horizontal
    panes:
      - echo "Hello"

# sample-2.yml
windows:
  - root: /Users/foo
    name: sample-2
    layout: even-horizontal
    panes:
      - echo "Hello"

# sample-3.yml
windows:
  - root: /Users/foo
    name: sample-2
    layout: even-horizontal
    panes:
      - echo "Hello"
```

And then you’ll be able to do this:

```bash
$ teamocil sample-1; teamocil sample-3
```
