### ISSUE TITLE
Fails to change directory under teamocil 1.4

### ISSUE THREAD

**Issue by jarednorman** [remiprev/teamocil#104]
```sh
~$ chruby 2.2.3
~$ teamocil --here --debug hater
tmux rename-session 'Hater'
tmux send-keys -t 1 'cd "/home/jared/Codes/hater"'
tmux send-keys -t 1 'Enter'
tmux rename-window 'editor'
tmux send-keys -t 1 'clear && g s'
tmux send-keys -t 1 'Enter'
tmux select-layout 'even-vertical'
tmux select-pane -t 1
tmux select-window -t 1
~$ chruby 2.3.0
~$ teamocil --here --debug hater
tmux rename-session 'Hater'
tmux send-keys -t 'editor.1' 'cd "/home/jared/Codes/hater"'
tmux send-keys -t 'editor.1' 'Enter'
tmux rename-window 'editor'
tmux send-keys -t 'editor.1' 'clear && g s'
tmux send-keys -t 'editor.1' 'Enter'
tmux select-layout -t 'editor' 'even-vertical'
tmux select-pane -t editor.1
tmux select-window -t 1
```
Config: 
```yaml
name: Hater
windows:
  - name: editor
    root: ~/Codes/hater
    focus: true
    layout: even-vertical
    panes:
      - clear && g s
```

The `g s` (just alias for `git status`) fails because the first (and in this case only) window would not be in a git repository. If I add additional windows they work as desired.
