### ISSUE TITLE
Cannot focus pane if window name contains spaces

### ISSUE THREAD

**Issue by garrettr** [remiprev/teamocil#114]
# Steps to reproduce

In `~/.teamocil/str.yml`:

```yml
windows:
  - name: window name with spaces
    layout: tiled
    panes:
      - commands:
          - echo "1"
        focus: true
      - commands:
          - echo "2"
```

Run `tmux`, then `teamocil str`.

## Expected behavior

Teamocil should switch to the first pane, which has `focus: true` set.

## Observed behavior

Teamocil keeps the second pane focused, seemingly ignoring `focus: true` on the first pane.

## Output of `teamocil --debug`

$ teamocil str --debug

```
tmux rename-session 'teamocil-session-587887'
tmux new-window -n 'window name with spaces'
tmux send-keys -t 'window name with spaces.0' 'echo "1"'
tmux send-keys -t 'window name with spaces.0' 'Enter'
tmux select-layout -t 'window name with spaces' 'tiled'
tmux split-window -t 'window name with spaces'
tmux send-keys -t 'window name with spaces.1' 'echo "2"'
tmux send-keys -t 'window name with spaces.1' 'Enter'
tmux select-layout -t 'window name with spaces' 'tiled'
tmux select-pane -t window name with spaces.0
```
