### ISSUE TITLE
Teamocil is wiping out GEM_HOME and GEM_PATH

### ISSUE THREAD

**Issue by bronzdoc** [remiprev/teamocil#117]
Hi :wave:, I'm trying to use teamocil, but it seems it is wiping out GEM_HOME and GEM_PATH before any command runs.

My teamocil window config named `dev` is the following:

```
name: dev

windows:
  - name: coding
    root: ~/projects/myproject
    layout: even-vertical
    panes:
      - commands:
        - rvm gemset use mygemset
        - git status
      - commands:
        - rvm gemset use mygemset
        - rails c

  - name: server
    root: ~/projects/myproject
    layout: even-horizontal
    panes:
      - psql -h localhost -U postgres -d dev_db
      - commands:
        - export USER=test
        - export PASSWORD=test
        - rvm gemset use mygemset
        - rails server
```

After running `teamocil dev`  i'll get the windows and panes as I wanted but rvm will display an error:

```
Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.1'.
System ruby is not controlled by RVM, but you can use it with 'rvm automount', read more: 'rvm help mount'.
```

I only get this behavior after running teamocil.

**Comment by remiprev** [comment]
Can you try to write the smallest layout possible that displays this error? There’s a lot going on in the one you pasted so if we want to isolate the error, it would be better to have a minimal layout to reproduce it. Thanks!

**Comment by bronzdoc** [comment]
I think this is the smallest layout to reproduce it @remiprev 

```
windows:
  - name: test
    root: ~/
    layout: even-vertical
    panes:
      - rvm gemset use test
```
