### ISSUE TITLE
Example using session

### ISSUE THREAD

**Issue by mblarsen** [remiprev/teamocil#122]
If would be nice with an example of defining session name. Tried a few variants with windows nested on sessions, tried with singular and plural sessions. 

All I really want to do is set the session name.

**Comment by dkrmr** [comment]
@mblarsen Here's an example:
``` yaml
name: sample-session
windows:
  - name: sample-two-panes
    root: ~/Code/sample/www
    layout: even-horizontal
    panes:
      - git status
      - rails server
```
