### ISSUE TITLE
Feature Request: Recreating panes on changes in the command

### ISSUE THREAD

**Issue by JIoJIaJIu** [remiprev/teamocil#126]
I would like to have ability to enforce changed commands to run again
For example
```
name: my-session
windows:
  - name: immutable
    panes:
      - sleep 60
  - name: mutable
    panes:
      - tail -f /my.log
``` 
```
teamocil --here my-session
```
then I edit the `yml` to
```
...
    panes:
      - tail -f /my.log -n 100
```

in the same tmux session execute
```
teamocil --replace my-session
```
and my `mutable` plane is going to be recreated
and with
```
teamocil --replace --force my-session
```
all windows and panes are going to be recreated
