### ISSUE TITLE
Ability to set environment variables

### ISSUE THREAD

**Issue by trombonehero** [remiprev/teamocil#127]
I have a Teamocil YAML file that contains a lot of snippets like:

```yaml
windows:
  - name: ...
    root: ...
    panes:
      - commands:
        - export CC=...
        - export CXX=...
        - export BUILD_ROOT=something/Debug
        - export PATH=...:something/Debug/bin
      - commands:
        - export CC=...
        - export CXX=...
        - export BUILD_ROOT=something/Release
        - export PATH=...:something/Release/bin
      - ...
```

This is fine when using `sh(1)` or compatible shells (bash, zsh...), but breaks with other shells (csh, fish) that prefer `setenv` or `set --export`. If Teamocil were to afford the ability to manipulate the environment via Ruby's `ENV` hash, I'd be able to write descriptions such as the following that work with different sorts of shells:

```yaml
windows:
  - name: ...
    root: ...
    env:
      CC: ...      # would apply to all panes in this window
      CXX: ..      # would apply to all panes in this window
    panes:
      - env:       # only need to specify vars specific to this pane:
          BUILD_ROOT: ...:something/Debug
          PATH: ...:something/Debug/bin
      - env:
          BUILD_ROOT: ...:something/Release
          PATH: ...:something/Release/bin
```
