### ISSUE TITLE
Feature request: setup commands

### ISSUE THREAD

**Issue by chrisfosterelli** [remiprev/teamocil#130]
Hello! I have a few panes which all depend on a set of commands being ran beforehand. However, if they all try to run the command at once it will be problematic.

I have "worked around" this by putting a sleep in all of the panes but one. This isn't amazing. I would love a syntax support like the following:

```
windows:
  - name: mywindow
    layout: even-vertical
    setup:
      - setupcommand 1
      - setupcommand 2
      - setupcommand 3
    panes:
      - command 1
      - command 2
      - command 3
```

In which the setup commands would execute before the pane commands.
