### ISSUE TITLE
Create tmux session instead of editing existing one

### ISSUE THREAD

**Issue by dangbert** [remiprev/teamocil#142]
It seems like teamocil defaults to editing an existing tmux session (not sure how it picks which one either).

Is there a way to have it create a new tmux session instead first?  As a workaround I'm doing: `tmux new -d -s tmpsess && teamocil --layout layout.yml`

Here's my example layout.yml:

````yml
name: mysess
windows:
  - name: tasks
    root: ~
    layout: tiled
    panes:
      - ./experiment.py -h
      - date && ./experiment.py -h
````
