### ISSUE TITLE
Session being renamed

### ISSUE THREAD

**Issue by alexkubica** [remiprev/teamocil#143]
I noticed a weird behavior where the session's name is renamed to `teamocil-session-(some random number)`.
Example:

<img width="671" alt="Screenshot 2023-08-17 at 13 24 16" src="https://github.com/remi/teamocil/assets/14129135/bc3265ce-3297-48cd-9187-37742f451698">

Also I use `tmux select-pane -T` to rename panes (which I would love to have support for in the configuration) and noticed it sometimes renames panes in other windows rather in the new one.

Unfortunately I'm not able to reproduce the second issue and I can't share my config.

Configuration file for reproducing:
```
windows:
  - name: test
    layout: tiled
    panes:
      - commands:
          - tmux select-pane -T pane-0 -t 0
      - commands:
          - tmux select-pane -T pane-1 -t 1

```
