### ISSUE TITLE
Command for first split not running

### ISSUE THREAD

**Issue by claytron** [remiprev/teamocil#19]
If I take the example from the documentation and generalize it a bit like this:

```
windows:
  - name: "my-first-window"
    root: "~/Desktop"
    filters:
      before: "echo rvm use 1.9.2"
      after: "echo 'I am done initializing this split.'"
    splits:
      - cmd: "echo first"
      - cmd: "echo second"
        width: 50
      - cmd:
          - "echo third command1"
          - "echo third command2"
        height: 50
```

I see the following happen:

```
$ <teamocil command>                 |   $ <teamocil command>
rvm use 1.9.2                        |   rvm use 1.9.2
second                               |   third command1
I am done initializing this split.   |   third command2
                                     |   I am done initializing this split.
                                     |
                                     |--------------------------------------
                                     |
                                     |  ## Nothing in this split
                                     |  $
                                     |
```

The first split that is defined never runs the teamocil command.
