### ISSUE TITLE
Add "clear" after split configuration

### ISSUE THREAD

**Issue by Valloric** [remiprev/teamocil#26]
Let's say I have something like the following in my configuration (taken from the README):

```
windows:
  - name: "my-first-window"
    root: "~/Projects/foo-www"
    filters:
      before: "rvm use 1.9.2"
      after: "echo 'I am done initializing this split.'"
    splits:
      - cmd: "git status"
      - cmd: "bundle exec rails server --port 4000"
        focus: true
        width: 50
```

In every split I will see the commands that teamocil has executed there to create that split. That is somewhat ugly, so I have resorted to adding `clear` as the first command to every `cmd`. It would be awesome if teamocil could do this by itself; I see no downsides to clearing the screen after such "plumbing" commands.
