### ISSUE TITLE
Pane height not respected

### ISSUE THREAD

**Issue by hal-gh** [remiprev/teamocil#39]
Thanks for the effort you have put into writing teamocil. It certainly makes my life a little easier! ;)

I have a couple of issues, although I am not certain whether they are actual bugs, or errors in my config. Apologies if it's the latter.

My requirement is:
- Open 3 windows
- win1 - leave as it is
- win2, with name "user" - split into 3 panes. The first pane should be positioned at the top, span the full-width of the window and consume 70% of its height. The other two should be below the first, with a height of 30% and be sharing the width 50/50
- win3, with name "root" - same layout as win2. Sync panesm and run "sudo -i"in all panes, ready to accept the password

I am aiming for a layout with a vertical 70/30 split, like the following:

```
|----------------------|
|                      |
|                      |
|                      |
|                      |
|                      |
|-----------|----------|
|           |          |
|-----------|----------|
```

However, teamocil produces a 50/50 split

Please see my config below.

Furthermore, after running teamocil, win1 always contains the following text:

```
~$ teamocil 
usage: show-window-options [-g] [-t target-window]
usage: show-window-options [-g] [-t target-window]
usage: show-window-options [-g] [-t target-window]
usage: show-window-options [-g] [-t target-window]
```

My config:

```
session:
  windows:
    - name: "user"
      clear: true
      root: "/home/mydir/"
      splits: 
        - height: 70
          target: top
        - width: 50
          height: 30
          target: bottom-left
        - width: 50
          height: 30
          target: bottom-right
    - name: "root"
      clear: true
      focus: true
      options:
        synchronize-panes: true
      root: "/home/mydir/"
      splits:
        - height: 70
          cmd: "sudo -i"
          target: top
        - width: 50
          height: 30
          cmd: "sudo -i"
          target: bottom-left
        - width: 50
          height: 30
          cmd: "sudo -i"
          target: bottom-right
```

If there is any info I've omitted, please let me know as I'm happy to provide it.

Btw, the examples directory is a bit sparse. It would be nice to have different types of examples, than all that are pretty much using the same options.

Furthermore, note that the docs state to use the "panes" directive. I think this has changed to "splits", as "panes" doesn't seem to work.

Cheers
