### ISSUE TITLE
Teamocil seems to be creating an additional window

### ISSUE THREAD

**Issue by killtheliterate** [remiprev/teamocil#46]
I've set up a yml file which launches configures my TMUX session nicely, though an additional window is already created, regardless of yml file. I've tried the most basic configuration, which ought to only create 3 windows, but it creates 4.

```
windows:
  - name: "a-window"
    panes:
      - cmd:
  - name: "another-window"
    layout: tiled
    panes:
      - cmd:
      - cmd:
  - name: "another-another-window"
    layout: main-vertical
    panes:
      - cmd:
      - cmd:
      - cmd:
```
