### ISSUE TITLE
focus: true not switching to correct window // pane?

### ISSUE THREAD

**Issue by thewatts** [remiprev/teamocil#52]
Here is my current template,

running as: `teamocil rails --here`

```
session:
  name: "rails"
  windows:
    - name: "CODE"
      layout: 8590,178x45,0,0{114x45,0,0,3,63x45,115,0,4}
      panes:
        - cmd: "vim"
          focus: true
        - cmd: "guard"
    - name: "SERVER"
      layout: even-horizontal
      panes:
        - cmd: rails s -p 3000
        - cmd: ""
```

It won't switch to the "vim" pane inside of "CODE", instead it stays in the "SERVER" window.

Am I doing something wrong?
