### ISSUE TITLE
why only the the commands of  panel 0 being processed?

### ISSUE THREAD

**Issue by kamelzcs** [remiprev/teamocil#65]
`tmux` and `teamocil tc` commands are used.
Then, only the first `whoami` being processed in the `panel 0`, in other three panels, no command being processed at all.  What's wrong with it?

`tc.yml` under  `~/.teamocil/`

```
windows:
  - name: TC
    root: /home/kamel/Code/study
    layout: tiled
    #layout: ba8a,211x49,0,0{165x49,0,0,19,45x49,166,0[45x14,166,0,21,45x34,166,15,22]}
    panes:
      - whoami
      - ls
      - vim
      - vim
```

`Tmux` version: 1.9a

`teamocil` version: 1.0.1

`ruby` version: 2.1.2p95 **installed with RVM**

`lsb_release -a`:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

`KDE version`: `4.13.2`
`Konsole version`: `2.13.2`

![teamocil](https://cloud.githubusercontent.com/assets/3021531/3886908/5f61e9b6-21e7-11e4-8a4b-8d36a96b0145.png)
