### ISSUE TITLE
teamocil --here does not create multiple windows

### ISSUE THREAD

**Issue by cmhamill** [remiprev/teamocil#7]
Teamocil fails for me when invoking it with the `--here` flag. I end up with one window whose shell has tried to execute every command in my yaml file; the end result is a mess. It works fine without the `--here` flag.

`teamocil` version 0.2.1

Tha yaml file in question looks like this; perhaps something is wrong with it.

``` yml
session:
  name: pim
  root: ~/
  windows:
    - name: mail
      root: ~/
      splits:
        - cmd: "sup-mail"
    - name: news
      root: ~/
      splits:
        - cmd: "newsbeuter"
    - name: chat
      root: ~/
      splits:
        - cmd: "irssi"
    - name: cal
      root: ~/
      splits:
        - cmd: "when"
    - name: todo
      root: ~/
      splits:
        - cmd: "task next"
```
