### ISSUE TITLE
first window root not being set properly

### ISSUE THREAD

**Issue by pklingem** [remiprev/teamocil#76]
the following is my config in `~/.teamocil/project.yml`:

```
name: project
windows:
  - name: server
    root: ~/code/project
    panes:
      - grunt
  - name: vim
    root: ~/code/project
    panes:
      - vim
  - name: terminal
    root: ~/code/project
    panes:
      - git status
```

when I do the following:

```
tmux
teamocil --here project
```

the first window's root directory is not set properly, it remains as `~/`
