### ISSUE TITLE
Windows' name is not set to its expected value

### ISSUE THREAD

**Issue by Taluu** [remiprev/teamocil#84]
Let's say I have the following config:

``` yaml
name: Random session                                                                                                                                                                                                      
windows:
  - name: Common
    root: ~/path/to/root
    layout: tiled
    focus: true
    panes:
      - first-panel
      - second-panel
```

The session name is correctly set, but the window name seems to be whatever the first panel command line was instead of expected "Common"
