### ISSUE TITLE
Execute Additional TMUX commands after init.

### ISSUE THREAD

**Issue by deanchen** [remiprev/teamocil#94]
Is it possible to run a TMUX command after a window has been created?

The width for the main vertical layout is narrow on large screens so I would like to widen it. Specifically I'd like to run **resize-pane -t 0 -x 200** after the window and layout are initialized.

**Comment by remiprev** [comment]
Have you tried to specify this exact command as one of your panes command?

```yaml
windows:
  - name: sample-three-panes
    root: ~/Code/sample/www
    layout: main-vertical
    panes:
      - commands:
        - vim
      - commands:
        - git pull
        - git status
      - commands:
        - rails server
        - tmux resize-pane -t 0 -x 200
```

**Comment by wusung** [comment]
In my environment, it is working to put tmux resize-pane in first line instead of last line. 

```yaml
 windows:                                   
   - name: three-panes                      
     root: ~/workspace                      
     layout: main-vertical                  
     panes:                                 
       - commands:                          
         - tmux resize-pane -t 1 -x 120     
         - vim                              
       - commands:                          
         - top                              
       - commands:
         - ls -l
```
